version: "3.8"

services: 
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        container_name: elasticsearch
        ports:
            - "9200:9200"
        networks:
            - elastic
        environment:
            - node.name=elasticsearch
            - cluster.name=es-docker-cluster
            - bootstrap.memory_lock=false
            - cluster.initial_master_nodes=elasticsearch
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.2
        container_name: kibana
        links:
            - "elasticsearch"
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        networks:
            - elastic
    fluentd:
        container_name: fluentd
        build: ./fluentd
        ports: 
            - 24224:24224
            - 24224:24224/udp
        volumes: 
            - ./fluentd/log:/fluentd/log
        networks: 
            - elastic
    metricbeat:
        image: docker.elastic.co/beats/metricbeat:7.9.2  
        container_name: metricbeat
        user: root
        environment:
            - setup.kibana.host=kibana:5601
            - dashboards.enable=true
            # - output.elasticsearch.hosts=["elasticsearch:9200"]
            # - logging.level=debug
            - system.hostfs=/hostfs
        networks: 
            - elastic
        volumes:
            - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
            - ./modules.d/:/usr/share/metricbeat/modules.d/
            - /var/run/docker.sock:/var/run/docker.sock
            - /:/hostfs:ro
        restart: on-failure
    
    pyspark:
        # image: jupyter/pyspark-notebook
        container_name: pyspark
        build: ./clusterizer
        ports:
            - "8888:8888"
            - "4040-4080:4040-4080"
        volumes:
            - ./clusterizer:/home/jovyan/work/
        networks: 
            - elastic

    spark:
        # container_name: spark-master
        # build: ./spark
        image: bitnami/spark:3-debian-10
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        ports:
            - '7070:7070'
        networks: 
            - elastic
    spark-worker-1:
        # container_name: spark-worker-1
        # build: ./spark
        image: bitnami/spark:3-debian-10
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        networks: 
            - elastic
    spark-worker-2:
        # container_name: spark-worker-2
        # build: ./spark
        image: bitnami/spark:3-debian-10
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        networks: 
            - elastic

networks:
    elastic:
        driver: bridge
