version: "3.8"

services: 
    fluentd:
        container_name: fluentd
        build: ./fluentd
        ports: 
            - 24224:24224
            - 24224:24224/udp
        volumes: 
            - ./fluentd/log:/fluentd/log
        links: 
            - "mongo"
    mongo:
        container_name: mongo
        image: mongo
    app:
        container_name: app
        restart: always
        build: ./express
        ports:
          - "4000:4000"
        links:
          - mongo
        depends_on:
          - mongo

    