version: "3.8"

services: 
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        container_name: elasticsearch
        ports:
            - "9200:9200"
        networks:
            - elastic
        environment:
            - node.name=elasticsearch
            - cluster.name=es-docker-cluster
            - bootstrap.memory_lock=false
            - cluster.initial_master_nodes=elasticsearch
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.2
        container_name: kibana
        links:
            - "elasticsearch"
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        networks:
            - elastic
    fluentd:
        container_name: fluentd
        build: ./fluentd
        ports: 
            - 24224:24224
            - 24224:24224/udp
        volumes: 
            - ./fluentd/log:/fluentd/log
        networks: 
            - elastic
    metricbeat:
        image: docker.elastic.co/beats/metricbeat:7.9.2  
        container_name: metricbeat
        user: root
        environment:
            - setup.kibana.host=kibana:5601
            - setup.dashboards.enable=true
            - system.hostfs=/hostfs
        networks: 
            - elastic
        volumes:
            - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
            - ./modules.d/:/usr/share/metricbeat/modules.d/
            - /var/run/docker.sock:/var/run/docker.sock
            - /:/hostfs:ro
        restart: on-failure
networks:
    elastic:
        driver: bridge
