version: "3.8"

services: 
    fluentd:
        image: fluentd:v1.11-debian-1
        ports: 
            - 24224:24224
            - 24224:24224/udp
        volumes: 
            - ./log:/fluentd/log
        