version: "3.8"

services: 
    elasticsearch:
        image: elasticsearch:6.8.12
        expose:
          - 9200
        ports:
          - "9200:9200"
    kibana:
        image: kibana:6.8.12
        links:
          - "elasticsearch"
        ports:
          - "5601:5601"
        depends_on: 
          - elasticsearch
    fluentd:
        container_name: fluentd
        build: ./fluentd
        ports: 
            - 24224:24224
            - 24224:24224/udp
        volumes: 
            - ./fluentd/log:/fluentd/log
        links: 
            - "elasticsearch"
        depends_on: 
            - elasticsearch
            

    