version: "3.8"

services: 
    fluentd:
        build: ./fluentd
        ports: 
            - 24224:24224
            - 24224:24224/udp
        volumes: 
            - ./fluentd/log:/fluentd/log
    mongo:
        image: mongo

    